server.:
  port: 61081
  servlet:
    context-path: /wetest

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wetest?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456



